# Generated by Django 3.0.4 on 2020-03-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.TextField()),
                ('place_id', models.TextField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('user_rating', models.FloatField()),
                ('num_ratings', models.IntegerField()),
            ],
        ),
    ]
