# Generated by Django 3.0.4 on 2020-03-15 01:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
