# Generated by Django 3.0.4 on 2020-03-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='gift_card_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_url',
            field=models.URLField(null=True),
        ),
    ]
