# Generated by Django 3.0.4 on 2020-03-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200315_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='gift_card_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
