# Generated by Django 3.0.4 on 2020-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20200315_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
