# Generated by Django 3.0.4 on 2020-03-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_place_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_attribution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
