# Generated by Django 3.0.4 on 2020-03-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_neighborhood_photo_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
