# Generated by Django 3.0.4 on 2020-03-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_emailsubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsubscription',
            old_name='place_id',
            new_name='place',
        ),
    ]
