# Generated by Django 3.0.4 on 2020-03-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='dummy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
