# Generated by Django 3.0.4 on 2020-03-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='dummy',
        ),
    ]
