# Generated by Django 3.0.4 on 2020-03-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200315_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.TextField(default='moop'),
            preserve_default=False,
        ),
    ]
