# Generated by Django 3.0.4 on 2020-03-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20200315_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('name', models.TextField()),
                ('key', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Neighborhood')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='places',
            field=models.ManyToManyField(through='places.NeighborhoodEntry', to='places.Place'),
        ),
    ]
