# Generated by Django 3.0.4 on 2020-03-18 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20200317_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Area'),
        ),
    ]
