# Generated by Django 3.0.4 on 2020-03-18 21:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_auto_20200318_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='bounds',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
