# Generated by Django 3.0.4 on 2020-03-19 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_auto_20200319_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedgiftcardlink',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
