# Generated by Django 3.0.4 on 2020-03-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_submittedgiftcardlink_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
