# Generated by Django 3.0.4 on 2020-03-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_neighborhood_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_card_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('place_id', models.TextField()),
                ('place_name', models.TextField()),
                ('place_rough_location', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
