# Generated by Django 3.0.4 on 2020-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_submittedplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedplace',
            name='website',
        ),
        migrations.AddField(
            model_name='submittedplace',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
