# Generated by Django 3.0.4 on 2020-03-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0025_auto_20200320_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedplace',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
