# Generated by Django 3.0.4 on 2020-03-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0026_submittedplace_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='gift_card_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
