# Generated by Django 3.0.4 on 2020-03-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0027_auto_20200321_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submittedgiftcardlink',
            name='link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='submittedplace',
            name='gift_card_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
