# Generated by Django 3.0.4 on 2020-03-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0028_auto_20200322_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_types',
            field=models.TextField(blank=True, null=True),
        ),
    ]
