# Generated by Django 3.0.4 on 2020-03-23 16:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_place_place_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='donation_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='takeout_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
