# Generated by Django 3.0.4 on 2020-03-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0030_auto_20200323_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscription',
            name='sent_to_place_owner',
        ),
    ]
