# Generated by Django 3.0.4 on 2020-03-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0031_remove_emailsubscription_sent_to_place_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedplace',
            name='matched_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
